"use client";

import { Home, LayoutGrid, Search, ShoppingCart, UserRound } from "lucide-react";
import Link from "next/link";
import { useCommerce } from "@/components/commerce/commerce-provider";

export function SiteFooter() { return <footer className="bg-[linear-gradient(120deg,#062b68_0%,#0872f5_64%,#7047eb_120%)] pb-24 pt-9 text-white md:pb-7"><div className="mx-auto grid max-w-[1200px] gap-7 px-4 md:grid-cols-2 md:px-0 lg:grid-cols-5"><div><div className="flex items-center gap-2"><span className="grid size-10 -rotate-3 place-items-center rounded-xl bg-white text-2xl font-black italic text-[#0872f5] shadow-[3px_3px_0_#ffd83d]">V</span><p className="text-2xl font-black">SALE</p></div><p className="mt-3 text-xs leading-5 text-white/75">ครบเรื่องเรียนและงาน<br/>ช้อปง่าย โปรดี ส่งทั่วไทย</p></div><FooterGroup title="เลือกซื้อสินค้า" links={["สินค้าทั้งหมด","โปรโมชั่น","สินค้าขายดี","สินค้าใหม่","หมวดหมู่"]}/><FooterGroup title="ช่วยเหลือลูกค้า" links={["ติดตามคำสั่งซื้อ","การจัดส่ง","การคืนสินค้า","คำถามที่พบบ่อย","ติดต่อเรา"]}/><FooterGroup title="เกี่ยวกับ V SALE" links={["เกี่ยวกับเรา","นโยบายความเป็นส่วนตัว","ข้อกำหนดการใช้งาน"]}/><div><h2 className="text-sm font-black text-[#fff06a]">พร้อมช่วยทุกคำสั่งซื้อ</h2><p className="mt-3 text-xs leading-5 text-white/75">สอบถามเรื่องสินค้า การจัดส่ง และการสั่งซื้อจำนวนมากได้กับทีม V SALE</p></div></div><div className="mx-auto mt-7 flex max-w-[1200px] flex-wrap justify-between gap-3 border-t border-white/18 px-4 pt-4 text-[10px] text-white/65 md:px-0"><span>© 2026 V SALE สงวนลิขสิทธิ์</span><span>ชำระเงินปลอดภัย · จัดส่งทั่วไทย</span></div></footer>; }
function FooterGroup({ title, links }: { title: string; links: string[] }) { return <div><h2 className="text-sm font-bold">{title}</h2><ul className="mt-2 space-y-1.5 text-xs text-white/70">{links.map((label) => <li key={label}><Link className="hover:text-white" href="#">{label}</Link></li>)}</ul></div>; }

export function MobileBottomNav() {
  const { cartCount, openCart, favorites } = useCommerce();
  return <nav aria-label="เมนูล่างมือถือ" className="fixed inset-x-0 bottom-0 z-40 grid h-[64px] grid-cols-5 border-t border-[#dce2ec] bg-white/97 px-1 pb-[env(safe-area-inset-bottom)] shadow-[0_-8px_25px_rgba(22,54,98,.10)] backdrop-blur md:hidden"><NavItem icon={<Home/>} label="หน้าแรก" href="/"/><NavItem icon={<LayoutGrid/>} label="หมวดหมู่" href="#categories"/><NavItem icon={<Search/>} label="ค้นหา" href="#top"/><button className="relative grid min-h-11 place-content-center justify-items-center gap-0.5 text-[10px] font-bold text-[#0872f5]" onClick={(event) => openCart(event.currentTarget)}><span className="grid size-8 place-items-center rounded-full bg-[#e8f3ff]"><ShoppingCart className="size-4.5"/></span>{cartCount > 0 && <span className="absolute right-[24%] top-1 min-w-4 rounded-full bg-[#ff4361] px-1 text-white">{cartCount}</span>}ตะกร้า</button><NavItem icon={<UserRound/>} label={favorites.size ? `โปรด ${favorites.size}` : "บัญชี"} href="/account"/></nav>;
}
function NavItem({ icon, label, href }: { icon: React.ReactNode; label: string; href: string }) { return <Link href={href} className="grid min-h-11 place-content-center justify-items-center gap-0.5 text-[10px] font-semibold text-[#415875] [&_svg]:size-5">{icon}{label}</Link>; }
