"use client";

import { Send } from "lucide-react";
import { FormEvent, useState } from "react";

export function NewsletterSection() {
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<"idle"|"loading"|"success"|"duplicate"|"error">("idle");
  async function submit(event: FormEvent) { event.preventDefault(); setStatus("loading"); try { const response = await fetch("/api/newsletter", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email }) }); const data = await response.json(); setStatus(response.ok ? (data.duplicate ? "duplicate" : "success") : "error"); } catch { setStatus("error"); } }
  return <section id="contact" className="compact-section mx-auto max-w-[1200px] px-4 md:px-0"><div className="relative grid gap-4 overflow-hidden rounded-[24px] bg-[linear-gradient(105deg,#d94700_0%,#ff6b00_62%,#ff9b19_120%)] p-5 text-white md:grid-cols-[1fr_1.2fr] md:items-center md:px-7"><span className="absolute -right-10 -top-16 size-44 rounded-full border-[25px] border-[#ffd83d]/32"/><div className="relative flex items-center gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-[#ffd83d] text-[#4a2b1b]"><Send className="size-6"/></span><div><h2 className="text-xl font-black">ของใหม่และโปรดี ส่งตรงถึงคุณ</h2><p className="text-xs text-white/82">ไม่พลาดสินค้าเข้าใหม่และข้อเสนอจาก V SALE</p></div></div><form onSubmit={submit} className="relative"><div className="flex flex-col gap-2 sm:flex-row"><label className="flex-1"><span className="sr-only">อีเมล</span><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="กรอกอีเมลของคุณ" className="min-h-11 w-full rounded-xl border border-white/40 bg-white px-4 text-sm text-[#4a2b1b] outline-none focus:border-[#ffd83d]"/></label><button disabled={status === "loading"} className="min-h-11 rounded-xl bg-[#ffd83d] px-6 text-sm font-black text-[#4a2b1b] disabled:opacity-60">{status === "loading" ? "กำลังสมัคร..." : "รับโปรก่อนใคร"}</button></div><p aria-live="polite" className="mt-1 min-h-4 text-[10px] text-white/75">{status === "success" ? "สมัครรับข่าวสารเรียบร้อยแล้ว" : status === "duplicate" ? "อีเมลนี้สมัครไว้แล้ว" : status === "error" ? "ยังสมัครไม่ได้ กรุณาลองใหม่" : "เมื่อสมัคร คุณยอมรับนโยบายความเป็นส่วนตัวของร้าน"}</p></form></div></section>;
}
