import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Box, Star, Truck } from "lucide-react";
import { Reveal } from "@/components/motion/reveal";
import type { HomeCategory, HomePromotion, HomeReview } from "@/types/commerce";

export function HeroSection() { return <section className="bg-[#eaf2ff]"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-[5fr_7fr]"><div className="flex flex-col justify-center px-4 py-12 md:px-8 lg:px-12 lg:py-16"><Reveal><p className="text-sm font-bold text-[#146ef5]">V SALE · ครบเรื่องเรียนและงาน</p></Reveal><Reveal delay={.07}><h1 className="mt-3 max-w-xl text-[clamp(2.25rem,5vw,4.5rem)] font-black leading-[1.02] tracking-[-.04em] text-[#0b1533]">ทุกอย่างพร้อม<br/>ให้ทุกวันไปต่อ</h1></Reveal><Reveal delay={.14}><p className="mt-5 max-w-xl text-base leading-7 text-[#4e5c75] md:text-lg">เครื่องเขียน หนังสือ แบบฟอร์ม ศิลปะ และอุปกรณ์สำนักงาน เพื่อการเรียนรู้และการทำงานที่ดีกว่าในทุกวัน</p></Reveal><Reveal delay={.21} className="mt-7 flex flex-wrap gap-3"><Link href="#products" className="inline-flex min-h-12 items-center gap-3 rounded-full bg-[#146ef5] px-6 font-bold text-white shadow-lg shadow-blue-600/15">เลือกซื้อสินค้า <ArrowRight className="size-4"/></Link><Link href="#new-arrivals" className="inline-flex min-h-12 items-center rounded-full border border-[#146ef5] px-6 font-bold text-[#146ef5]">ดูสินค้าใหม่</Link></Reveal></div><Reveal className="relative min-h-[320px] md:min-h-[480px] lg:min-h-[560px]"><Image src="/images/vsale/hero-home.png" alt="เครื่องเขียน หนังสือ สี และอุปกรณ์สำหรับการเรียนและสำนักงาน" fill priority sizes="(max-width: 1023px) 100vw, 58vw" className="hero-float object-cover object-center"/></Reveal></div></section>; }

export function SectionHeading({ eyebrow, title, linkLabel, href = "#products" }: { eyebrow?: string; title: string; linkLabel?: string; href?: string }) { return <div className="mb-7 flex items-end justify-between gap-4"><div>{eyebrow && <p className="mb-1 text-xs font-bold tracking-wider text-[#146ef5]">{eyebrow}</p>}<h2 className="text-[clamp(1.65rem,3vw,2.6rem)] font-black tracking-[-.035em] text-[#0b1533]">{title}</h2></div>{linkLabel && <Link href={href} className="hidden min-h-11 items-center gap-2 py-3 text-sm font-bold text-[#146ef5] sm:flex">{linkLabel}<ArrowRight className="size-4"/></Link>}</div>; }

export function CategoryGrid({ categories }: { categories: HomeCategory[] }) { return <Reveal><section id="categories" aria-labelledby="categories-title" className="mx-auto max-w-[1440px] px-4 py-14 md:px-6 lg:px-12"><h2 id="categories-title" className="sr-only">หมวดหมู่สินค้า</h2><div className="category-rail flex gap-3 overflow-x-auto pb-3">{categories.map((category) => <Link id={`category-${category.slug}`} key={category.id} href={`#products`} className="group w-[104px] shrink-0 scroll-ml-4 text-center md:w-[128px]"><div className="relative aspect-square overflow-hidden rounded-full bg-[#eaf2ff] transition duration-200 group-hover:-translate-y-1 group-focus-visible:-translate-y-1"><Image src={category.image.src} alt={category.image.alt} fill sizes="128px" className="object-cover transition-transform duration-200 group-hover:scale-[1.03]"/></div><h3 className="mt-3 text-xs font-semibold leading-5 text-[#0b1533] md:text-sm">{category.name}</h3></Link>)}</div></section></Reveal>; }

export function TrustBenefits() { const items = [{ icon: <Star/>, title: "เลือกง่าย ใช้งานตรงจุด", detail: "แบ่งหมวดสำหรับการเรียน การสอน และสำนักงาน" },{ icon: <Box/>, title: "ข้อมูลสินค้าชัดเจน", detail: "ดูราคา สต็อก และสถานะสินค้าได้ก่อนเลือกซื้อ" },{ icon: <Truck/>, title: "จัดส่งทั่วไทย", detail: "รองรับทั้งรายการทั่วไปและการสั่งซื้อจำนวนมาก" }]; return <section aria-label="ข้อมูลร้าน" className="mx-auto max-w-[1440px] px-4 md:px-6 lg:px-12"><div className="grid rounded-2xl bg-[#eef5ff] md:grid-cols-3">{items.map((item, index) => <div key={item.title} className={`flex min-w-0 items-center gap-4 px-5 py-5 ${index ? "border-t border-[#d5e3f5] md:border-l md:border-t-0" : ""}`}><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-white text-[#146ef5] [&_svg]:size-6">{item.icon}</span><span className="min-w-0"><b className="block">{item.title}</b><small className="text-[#667085]">{item.detail}</small></span></div>)}</div></section>; }

export function PromotionGrid({ promotions }: { promotions: HomePromotion[] }) { return <Reveal><section id="promotions" className="section-pad mx-auto max-w-[1440px] px-4 md:px-6 lg:px-12"><SectionHeading title="เลือกง่าย ได้คุ้มกว่า" linkLabel="ดูโปรโมชั่นทั้งหมด"/><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-[1.15fr_.7fr_.85fr] lg:grid-rows-2">{promotions.map((promotion, index) => <Link key={promotion.id} href={promotion.href} className={`group relative min-h-[230px] overflow-hidden rounded-2xl ${index === 0 ? "md:min-h-[430px] lg:row-span-2" : ""} ${index === 1 ? "lg:row-span-2" : ""}`}><Image src={promotion.image.src} alt={promotion.image.alt} fill sizes={index < 2 ? "(max-width: 1023px) 100vw, 40vw" : "(max-width: 1023px) 100vw, 28vw"} className="object-cover transition-transform duration-300 group-hover:scale-[1.025]"/><span className="absolute inset-0 bg-gradient-to-t from-[#071b3b]/70 via-transparent to-transparent"/><span className="absolute inset-x-0 bottom-0 p-5 text-white"><small>{promotion.subtitle}</small><strong className="mt-1 flex items-center justify-between text-2xl">{promotion.title}<ArrowRight className="size-5 transition-transform group-hover:translate-x-1"/></strong></span></Link>)}</div></section></Reveal>; }

export function EditorialBanner() { return <Reveal><section className="mx-auto max-w-[1440px] px-4 md:px-6 lg:px-12"><div className="relative min-h-[440px] overflow-hidden rounded-3xl md:min-h-[370px]"><Image src="/images/vsale/banners/editorial-desk.png" alt="โต๊ะทำงานที่จัดอย่างเป็นระเบียบพร้อมแฟ้มและเครื่องเขียน" fill sizes="(max-width: 767px) 100vw, 1320px" className="object-cover object-[62%_center]"/><div className="absolute inset-0 bg-gradient-to-r from-white via-white/85 to-transparent"/><div className="absolute inset-y-0 left-0 flex max-w-xl flex-col justify-center p-7 md:p-12"><h2 className="text-3xl font-black leading-tight text-[#0b1533] md:text-5xl">จัดโต๊ะใหม่<br/>ให้ไอเดียไหลลื่น</h2><p className="mt-4 max-w-md text-[#4e5c75]">อุปกรณ์สำนักงาน เอกสาร เทป กาว และของใช้ทุกวัน เพื่อพื้นที่ทำงานที่เป็นระเบียบและมีประสิทธิภาพมากขึ้น</p><Link href="#products" className="mt-6 inline-flex min-h-12 w-fit items-center gap-3 rounded-full bg-[#146ef5] px-6 font-bold text-white">เลือกดูอุปกรณ์สำนักงาน <ArrowRight className="size-4"/></Link></div></div></section></Reveal>; }

const useCases = [["วันเรียน","อุปกรณ์ครบ พร้อมลุยทุกวิชา","use-student.png"],["วันสอน","สื่อการสอน เอกสาร และอุปกรณ์","use-teacher.png"],["วันทำงาน","จัดระเบียบงาน ให้สำเร็จทุกชิ้น","use-office.png"],["วันสร้างสรรค์","ศิลปะและงานฝีมือ จุดไอเดียใหม่","use-creative.png"]];
export function ShopByUseSection() { return <Reveal><section className="section-pad mx-auto max-w-[1440px] px-4 md:px-6 lg:px-12"><SectionHeading title="เลือกตามวันของคุณ"/><div className="category-rail flex snap-x gap-3 overflow-x-auto pb-3 lg:grid lg:grid-cols-4">{useCases.map(([title, copy, image]) => <Link key={title} href="#products" className="group relative min-h-[260px] w-[82vw] max-w-sm shrink-0 snap-start overflow-hidden rounded-2xl sm:w-[46vw] lg:w-auto"><Image src={`/images/vsale/lifestyle/${image}`} alt={`${title} ${copy}`} fill sizes="(max-width: 767px) 82vw, (max-width: 1023px) 46vw, 25vw" className="object-cover transition-transform duration-300 group-hover:scale-[1.03]"/><span className="absolute inset-0 bg-gradient-to-t from-[#071b3b]/75 via-transparent to-transparent"/><span className="absolute inset-x-0 bottom-0 p-5 text-white"><strong className="block text-xl">{title}</strong><small>{copy}</small></span></Link>)}</div></section></Reveal>; }

export function InstitutionalBanner() { return <Reveal><section id="institutional" className="mx-auto max-w-[1440px] px-4 md:px-6 lg:px-12"><div className="relative min-h-[430px] overflow-hidden rounded-3xl bg-[#eaf2ff] md:min-h-[340px]"><Image src="/images/vsale/banners/institutional-orders.png" alt="ห้องเรียนพร้อมกล่องอุปกรณ์สำหรับจัดส่งจำนวนมาก" fill sizes="(max-width: 767px) 100vw, 1320px" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#eaf2ff] via-[#eaf2ff]/95 to-transparent"/><div className="absolute inset-y-0 left-0 flex max-w-2xl flex-col justify-center p-7 md:p-12"><p className="text-xs font-bold text-[#146ef5]">สั่งซื้อจำนวนมาก</p><h2 className="mt-2 text-3xl font-black text-[#0b1533] md:text-5xl">สำหรับโรงเรียน<br/>และสำนักงาน</h2><p className="mt-4 max-w-lg text-[#4e5c75]">ต้องการสั่งสินค้าหลายรายการหรือจำนวนมาก ส่งรายละเอียดมาให้ร้านตรวจสอบและเสนอราคาได้</p><Link href="#contact" className="mt-6 inline-flex min-h-12 w-fit items-center gap-3 rounded-full bg-[#146ef5] px-6 font-bold text-white">สอบถามการสั่งซื้อ <ArrowRight className="size-4"/></Link></div></div></section></Reveal>; }

export function CustomerReviews({ reviews }: { reviews: HomeReview[] }) { if (!reviews.length) return null; return <Reveal><section className="section-pad mx-auto max-w-[1440px] px-4 md:px-6 lg:px-12"><SectionHeading title="เสียงจากลูกค้า"/><div className="grid gap-4 md:grid-cols-3">{reviews.map((review) => <article key={review.id} className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[#eaf2ff] font-bold text-[#146ef5]">{review.authorInitial}</span><span><span className="block text-[#f4a600]">{"★".repeat(review.rating)}</span>{review.verified && <small className="text-[#16855b]">ซื้อแล้ว</small>}</span></div><p className="mt-4 leading-7 text-[#4e5c75]">“{review.excerpt}”</p></article>)}</div></section></Reveal>; }
