import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Box, CheckCircle2, Palette, Star, Truck } from "lucide-react";
import { Reveal } from "@/components/motion/reveal";
import type { HomeCategory, HomePromotion, HomeReview } from "@/types/commerce";

export function HeroSection() {
  return <section className="px-3 pb-7 pt-3 md:px-6 md:pb-10 lg:px-10">
    <div className="relative mx-auto grid max-w-[1360px] overflow-hidden rounded-[2rem] bg-[#dfeeff] shadow-[0_24px_70px_rgba(22,76,148,.13)] lg:grid-cols-[5fr_7fr]">
      <div className="absolute -left-20 -top-20 size-56 rounded-full bg-[#ffcc58]/55 blur-2xl"/><div className="absolute bottom-[-90px] left-[34%] size-64 rounded-full bg-[#ff7968]/25 blur-3xl"/>
      <div className="relative z-10 flex flex-col justify-center px-6 py-12 md:px-10 lg:px-12 lg:py-16">
        <Reveal><p className="inline-flex w-fit items-center gap-2 rounded-full bg-white/80 px-3 py-1.5 text-xs font-extrabold text-[#1268f3] shadow-sm"><Palette className="size-4"/>V SALE · ครบเรื่องเรียนและงาน</p></Reveal>
        <Reveal delay={0.07}><h1 className="mt-5 max-w-xl text-[clamp(2.5rem,5vw,4.8rem)] font-extrabold leading-[1.08] tracking-[-.045em] text-[#071b3b]">ทุกอย่างพร้อม<br/><span className="text-[#1268f3]">ให้ทุกวันไปต่อ</span></h1></Reveal>
        <Reveal delay={0.14}><p className="mt-5 max-w-xl text-[17px] leading-8 text-[#405675]">เครื่องเขียน หนังสือ แบบฟอร์ม ศิลปะ และอุปกรณ์สำนักงาน เลือกง่าย ใช้ได้จริงในทุกวัน</p></Reveal>
        <Reveal delay={0.21} className="mt-7 flex flex-wrap gap-3"><Link href="#products" className="inline-flex min-h-12 items-center gap-3 rounded-xl bg-[#1268f3] px-6 font-bold text-white shadow-[0_10px_24px_rgba(18,104,243,.26)]">เลือกซื้อสินค้า <ArrowRight className="size-4"/></Link><Link href="#new-arrivals" className="inline-flex min-h-12 items-center rounded-xl border-2 border-white bg-white/70 px-6 font-bold text-[#1268f3]">ดูสินค้าใหม่</Link></Reveal>
        <Reveal delay={0.28} className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-sm font-semibold text-[#314b70]"><span className="inline-flex items-center gap-2"><CheckCircle2 className="size-4 text-[#20a77d]"/>ครบเรื่องเรียน</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="size-4 text-[#20a77d]"/>พร้อมเรื่องงาน</span></Reveal>
      </div>
      <Reveal className="relative min-h-[330px] md:min-h-[480px] lg:min-h-[590px]"><Image src="/images/vsale/hero-home.png" alt="เครื่องเขียน หนังสือ สี และอุปกรณ์สำหรับการเรียนและสำนักงาน" fill priority sizes="(max-width: 1023px) 100vw, 58vw" className="hero-float object-cover object-center"/></Reveal>
    </div>
  </section>;
}

export function SectionHeading({ eyebrow, title, linkLabel, href = "#products", copy }: { eyebrow?: string; title: string; linkLabel?: string; href?: string; copy?: string }) {
  return <div className="mb-7 flex items-end justify-between gap-4 md:mb-9"><div className="min-w-0">{eyebrow && <p className="mb-2 text-xs font-extrabold tracking-[.16em] text-[#1268f3]">{eyebrow}</p>}<h2 className="text-[clamp(1.8rem,3.2vw,2.8rem)] font-extrabold leading-tight tracking-[-.035em] text-[#0a1d40]">{title}</h2>{copy && <p className="mt-2 text-[15px] leading-6 text-[#52627a]">{copy}</p>}</div>{linkLabel && <Link href={href} className="hidden min-h-11 shrink-0 items-center gap-2 rounded-full bg-[#e7f0ff] px-4 py-3 text-sm font-bold text-[#1268f3] sm:flex">{linkLabel}<ArrowRight className="size-4"/></Link>}</div>;
}

const categoryTones = ["bg-[#dceaff]", "bg-[#fff0be]", "bg-[#ffe0da]", "bg-[#d9f8ee]", "bg-[#ebe3ff]", "bg-[#dfe7ff]", "bg-[#ffe1e7]", "bg-[#e4f7ff]", "bg-[#e8f7d9]"];
export function CategoryGrid({ categories }: { categories: HomeCategory[] }) {
  return <Reveal><section id="categories" aria-labelledby="categories-title" className="mx-auto max-w-[1360px] px-4 py-12 md:px-6 md:py-16 lg:px-10"><SectionHeading eyebrow="SHOP BY CATEGORY" title="ช้อปตามหมวดที่ต้องใช้" copy="หาอุปกรณ์สำหรับเรียน สอน และทำงานได้เร็วขึ้น"/><div className="category-rail flex gap-3 overflow-x-auto pb-4 sm:gap-4">{categories.map((category, index) => <Link id={`category-${category.slug}`} key={category.id} href="#products" className="group w-[124px] shrink-0 scroll-ml-4 text-center md:w-[142px]"><div className={`relative aspect-square overflow-hidden rounded-[1.7rem] ${categoryTones[index % categoryTones.length]} shadow-[0_10px_28px_rgba(19,58,107,.09)] transition duration-200 group-hover:-translate-y-1`}><Image src={category.image.src} alt={category.image.alt} fill sizes="142px" className="object-cover transition-transform duration-300 group-hover:scale-[1.04]"/></div><h3 className="mt-3 text-[13px] font-bold leading-6 text-[#0a1d40] md:text-sm">{category.name}</h3></Link>)}</div></section></Reveal>;
}

export function TrustBenefits() {
  const items = [{ icon: <Star/>, tone: "bg-[#fff3c9] text-[#a66a00]", title: "เลือกง่าย ใช้งานตรงจุด", detail: "แบ่งหมวดตามงานที่คุณทำ" }, { icon: <Box/>, tone: "bg-[#dff0ff] text-[#1268f3]", title: "ข้อมูลสินค้าชัดเจน", detail: "เช็กราคาและสถานะก่อนเลือก" }, { icon: <Truck/>, tone: "bg-[#dff8ee] text-[#16845f]", title: "จัดส่งทั่วไทย", detail: "รองรับทั้งชิ้นเดียวและจำนวนมาก" }];
  return <section aria-label="ข้อมูลร้าน" className="mx-auto max-w-[1360px] px-4 pb-8 md:px-6 lg:px-10"><div className="grid gap-3 md:grid-cols-3">{items.map((item) => <div key={item.title} className="flex min-w-0 items-center gap-4 rounded-2xl border border-[#e0e9f6] bg-white px-5 py-5 shadow-[0_10px_28px_rgba(19,58,107,.07)]"><span className={`grid size-12 shrink-0 place-items-center rounded-xl ${item.tone} [&_svg]:size-6`}>{item.icon}</span><span className="min-w-0"><b className="block text-[15px] text-[#0a1d40]">{item.title}</b><small className="mt-1 block text-[13px] leading-5 text-[#60708a]">{item.detail}</small></span></div>)}</div></section>;
}

export function PromotionGrid({ promotions }: { promotions: HomePromotion[] }) {
  return <Reveal><section id="promotions" className="section-pad mx-auto max-w-[1360px] px-4 md:px-6 lg:px-10"><SectionHeading eyebrow="SMART DEALS" title="เลือกง่าย ได้คุ้มกว่า" copy="โปรเด่นสำหรับวันเรียน วันสอน และวันทำงาน" linkLabel="ดูโปรโมชั่นทั้งหมด"/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-[1.15fr_.72fr_.88fr] lg:grid-rows-2">{promotions.map((promotion, index) => <Link key={promotion.id} href={promotion.href} className={`group relative min-h-[240px] overflow-hidden rounded-[1.7rem] shadow-[0_16px_38px_rgba(14,54,105,.12)] ${index === 0 ? "md:min-h-[440px] lg:row-span-2" : ""} ${index === 1 ? "lg:row-span-2" : ""}`}><Image src={promotion.image.src} alt={promotion.image.alt} fill sizes={index < 2 ? "(max-width: 1023px) 100vw, 40vw" : "(max-width: 1023px) 100vw, 28vw"} className="object-cover transition-transform duration-500 group-hover:scale-[1.035]"/><span className="absolute inset-0 bg-gradient-to-t from-[#071b3b]/82 via-[#071b3b]/10 to-transparent"/><span className="absolute inset-x-0 bottom-0 p-5 text-white md:p-6"><small className="text-sm font-medium text-white/85">{promotion.subtitle}</small><strong className="mt-1 flex items-center justify-between text-2xl font-bold">{promotion.title}<ArrowRight className="size-5 transition-transform group-hover:translate-x-1"/></strong></span></Link>)}</div></section></Reveal>;
}

export function EditorialBanner() {
  return <Reveal><section className="mx-auto max-w-[1360px] px-4 py-5 md:px-6 lg:px-10"><div className="relative min-h-[460px] overflow-hidden rounded-[2rem] shadow-[0_22px_55px_rgba(15,57,113,.13)] md:min-h-[390px]"><Image src="/images/vsale/banners/editorial-desk.png" alt="โต๊ะทำงานที่จัดอย่างเป็นระเบียบพร้อมแฟ้มและเครื่องเขียน" fill sizes="(max-width: 767px) 100vw, 1320px" className="object-cover object-[62%_center]"/><div className="absolute inset-0 bg-gradient-to-r from-[#f8fbff] via-[#f8fbff]/92 to-transparent"/><div className="absolute inset-y-0 left-0 flex max-w-xl flex-col justify-center p-7 md:p-12"><p className="text-xs font-extrabold tracking-[.16em] text-[#1268f3]">WORKSPACE REFRESH</p><h2 className="mt-3 text-[clamp(2rem,4vw,3.4rem)] font-extrabold leading-tight tracking-[-.04em] text-[#0a1d40]">จัดโต๊ะใหม่<br/><span className="text-[#1268f3]">ให้ไอเดียไหลลื่น</span></h2><p className="mt-4 max-w-md text-[15px] leading-7 text-[#405675]">อุปกรณ์สำนักงาน เอกสาร เทป และกาว เพื่อพื้นที่ทำงานที่เป็นระเบียบและหยิบใช้สะดวก</p><Link href="#products" className="mt-6 inline-flex min-h-12 w-fit items-center gap-3 rounded-xl bg-[#1268f3] px-6 font-bold text-white">เลือกดูอุปกรณ์สำนักงาน <ArrowRight className="size-4"/></Link></div></div></section></Reveal>;
}

const useCases = [["วันเรียน", "อุปกรณ์ครบ พร้อมลุยทุกวิชา", "use-student.png", "bg-[#1268f3]"], ["วันสอน", "สื่อการสอน เอกสาร และอุปกรณ์", "use-teacher.png", "bg-[#ff6656]"], ["วันทำงาน", "จัดระเบียบงาน ให้สำเร็จทุกชิ้น", "use-office.png", "bg-[#6c54db]"], ["วันสร้างสรรค์", "ศิลปะและงานฝีมือ จุดไอเดียใหม่", "use-creative.png", "bg-[#12a87d]"]];
export function ShopByUseSection() {
  return <Reveal><section className="section-pad mx-auto max-w-[1360px] px-4 md:px-6 lg:px-10"><SectionHeading eyebrow="MADE FOR YOUR DAY" title="เลือกตามวันของคุณ" copy="แต่ละวันมีของที่ต้องใช้ต่างกัน เราจัดทางลัดไว้ให้แล้ว"/><div className="category-rail flex snap-x gap-4 overflow-x-auto pb-4 lg:grid lg:grid-cols-4">{useCases.map(([title, copy, image, tone]) => <Link key={title} href="#products" className="group relative min-h-[290px] w-[82vw] max-w-sm shrink-0 snap-start overflow-hidden rounded-[1.7rem] shadow-[0_16px_38px_rgba(14,54,105,.14)] sm:w-[46vw] lg:w-auto"><Image src={`/images/vsale/lifestyle/${image}`} alt={`${title} ${copy}`} fill sizes="(max-width: 767px) 82vw, (max-width: 1023px) 46vw, 25vw" className="object-cover transition-transform duration-500 group-hover:scale-[1.04]"/><span className="absolute inset-0 bg-gradient-to-t from-[#071b3b]/82 via-transparent to-transparent"/><span className={`absolute left-5 top-5 rounded-full px-3 py-1.5 text-xs font-bold text-white ${tone}`}>{title}</span><span className="absolute inset-x-0 bottom-0 p-5 text-white"><strong className="block text-2xl font-bold">{title}</strong><small className="mt-1 block text-[14px] text-white/90">{copy}</small></span></Link>)}</div></section></Reveal>;
}

export function InstitutionalBanner() {
  return <Reveal><section id="institutional" className="mx-auto max-w-[1360px] px-4 py-6 md:px-6 lg:px-10"><div className="relative min-h-[460px] overflow-hidden rounded-[2rem] bg-[#dfeeff] shadow-[0_22px_55px_rgba(15,57,113,.13)] md:min-h-[370px]"><Image src="/images/vsale/banners/institutional-orders.png" alt="ห้องเรียนพร้อมกล่องอุปกรณ์สำหรับจัดส่งจำนวนมาก" fill sizes="(max-width: 767px) 100vw, 1320px" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#dfeeff] via-[#dfeeff]/96 to-transparent"/><div className="absolute inset-y-0 left-0 flex max-w-2xl flex-col justify-center p-7 md:p-12"><p className="text-xs font-extrabold tracking-[.16em] text-[#1268f3]">BULK ORDER</p><h2 className="mt-3 text-[clamp(2rem,4vw,3.4rem)] font-extrabold leading-tight text-[#0a1d40]">สำหรับโรงเรียน<br/><span className="text-[#1268f3]">และสำนักงาน</span></h2><p className="mt-4 max-w-lg text-[15px] leading-7 text-[#405675]">ส่งรายการที่ต้องการให้ร้านช่วยตรวจสอบจำนวนและจัดข้อเสนอให้เหมาะกับการใช้งาน</p><Link href="#contact" className="mt-6 inline-flex min-h-12 w-fit items-center gap-3 rounded-xl bg-[#ff5b4d] px-6 font-bold text-white shadow-[0_10px_24px_rgba(255,91,77,.24)]">สอบถามการสั่งซื้อ <ArrowRight className="size-4"/></Link></div></div></section></Reveal>;
}

export function CustomerReviews({ reviews }: { reviews: HomeReview[] }) {
  if (!reviews.length) return null;
  return <Reveal><section className="section-pad mx-auto max-w-[1360px] px-4 md:px-6 lg:px-10"><SectionHeading eyebrow="CUSTOMER VOICES" title="เสียงจากลูกค้า"/><div className="grid gap-4 md:grid-cols-3">{reviews.map((review) => <article key={review.id} className="rounded-3xl border border-[#dce7f6] bg-white p-6 shadow-[0_12px_35px_rgba(16,52,101,.08)]"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-[#e4efff] font-bold text-[#1268f3]">{review.authorInitial}</span><span><span className="block text-[#f4a600]">{"★".repeat(review.rating)}</span>{review.verified && <small className="text-[#16855b]">ซื้อแล้ว</small>}</span></div><p className="mt-4 leading-7 text-[#405675]">“{review.excerpt}”</p></article>)}</div></section></Reveal>;
}
